name: Deploy React App to Windows

on:
  push:
    branches:
      - main # Deploy on push to the main branch

jobs:
  build:
    runs-on: self-hosted # Use your self-hosted runner on Windows

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v1

      # Step 2: Set up Node.js (installing Node.js for the runner)
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16" # Specify Node.js version

      # Step 3: Install dependencies (this will use Command Prompt on Windows by default)
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (run tests using npm test)
      - name: Run Tests
        run: npm test -- --watchAll=false

      # Step 5: Build the React application (build the app using npm)
      - name: Build the app
        run: npm run build

      # Step 6: Deploy the build to the local server directory (copy the built files to your specified folder)
      - name: Deploy to Local Server
        run: |
          xcopy /E /I /Y build\* "D:\A-CSPIT\A-Sem_5\ASP.Net\react-todo-app"
