name: Deploy React App to Windows

on:
  push:
    branches:
      - main # Deploy on push to the main branch

jobs:
  build:
    runs-on: self-hosted # Use self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Specify Node.js version

      - name: Install dependencies
        run: npm install # Will run using cmd

      - name: Run Tests
        run: npm test -- --watchAll=false # Will run using cmd

      - name: Build the app
        run: npm run build # Will run using cmd

      - name: Deploy to Local Server
        run: |
          xcopy /E /I /Y build\* "D:\A-CSPIT\A-Sem_5\ASP.Net\react-todo-app"
